from datetime import datetime, timedelta

# API CONFIG
EXCHANGE_NAME = "binance"
USE_FUTURES = False

# DATA CONFIG
TIMEFRAME = "1h"
DAYS_BACK = 90
CANDLE_LIMIT = DAYS_BACK * 24

# CLUSTER CONFIG (AUTO K)
MIN_K = 2
MAX_K = 10
RANDOM_STATE = 42

# CRYPTO LIST
SYMBOLS = [
    "BTC/USDT",
    "ETH/USDT",
    "BNB/USDT",
    "XRP/USDT",
    "USDC/USDT",
    "SOL/USDT",
    "TRX/USDT",
    "DOGE/USDT",
    "ADA/USDT",
    "BCH/USDT",
    "XMR/USDT",
    "LINK/USDT",
    "USDE/USDT",
    "DAI/USDT",
    "XLM/USDT",
    "USD1/USDT",
    "HBAR/USDT",
    "LTC/USDT",
    "AVAX/USDT",
    "ZEC/USDT",
    "SUI/USDT",
    "SHIB/USDT",
    "WLFI/USDT",
    "TON/USDT",
    "DOT/USDT",
    "PAXG/USDT",
    "UNI/USDT",
    "TAO/USDT",
    "ASTER/USDT",
    "AAVE/USDT",
    "SKY/USDT",
    "RLUSD/USDT",
    "NEAR/USDT",
    "PEPE/USDT",
    "ETC/USDT",
    "ICP/USDT",
    "ONDO/USDT",
    "POL/USDT",
    "WLD/USDT",
    "ATOM/USDT",
    "ENA/USDT",
    "TRUMP/USDT",
    "ALGO/USDT",
    "QNT/USDT",
    "FIL/USDT",
    "APT/USDT",
    "RENDER/USDT",
    "PUMP/USDT",
    "MORPHO/USDT",
    "U/USDT",
    "VET/USDT",
    "ARB/USDT",
    "JUP/USDT",
    "ZRO/USDT",
    "NEXO/USDT",
    "DCR/USDT",
    "BONK/USDT",
    "TUSD/USDT",
    "KITE/USDT",
    "STX/USDT",
    "SEI/USDT",
    "VIRTUAL/USDT",
    "CAKE/USDT",
    "PENGU/USDT",
    "DASH/USDT",
    "XTZ/USDT",
    "JST/USDT",
    "FDUSD/USDT",
    "ETHFI/USDT",
    "CRV/USDT",
    "LIT/USDT",
    "CHZ/USDT",
    "FET/USDT",
    "KAIA/USDT",
    "GNO/USDT",
    "BTT/USDT",
    "IMX/USDT",
    "BSV/USDT",
    "INJ/USDT",
    "SUN/USDT",
    "IOTA/USDT",
    "TIA/USDT",
    "PYTH/USDT",
    "DEXE/USDT",
    "GRT/USDT",
    "SYRUP/USDT",
    "JASMY/USDT",
    "FLOKI/USDT",
    "OP/USDT",
    "2Z/USDT",
    "LDO/USDT",
    "CFX/USDT",
    "LUNC/USDT",
    "SAND/USDT",
    "HNT/USDT",
    "ENS/USDT",
    "STRK/USDT",
    "BARD/USDT",
    "AXS/USDT",
    "TWT/USDT",
    "PENDLE/USDT",
    "WIF/USDT",
    "THETA/USDT",
    "MANA/USDT",
    "NEO/USDT",
    "FF/USDT",
    "COMP/USDT",
    "XPL/USDT",
    "CVX/USDT",
    "WAL/USDT",
    "ZK/USDT",
    "GALA/USDT",
    "RAY/USDT",
    "BAT/USDT",
    "SENT/USDT",
    "XEC/USDT",
    "RUNE/USDT",
    "BERA/USDT",
    "0G/USDT",
    "GLM/USDT",
    "SFP/USDT",
    "1INCH/USDT",
    "EGLD/USDT",
    "A/USDT",
    "AMP/USDT",
    "EIGEN/USDT",
    "COW/USDT",
    "JTO/USDT",
    "LPT/USDT",
    "S/USDT",
    "SNX/USDT",
    "STG/USDT",
    "GAS/USDT",
    "W/USDT",
    "AWE/USDT",
    "HOME/USDT",
    "AR/USDT",
    "TFUEL/USDT",
    "FOGO/USDT",
    "FTT/USDT",
    "QTUM/USDT",
    "ZEN/USDT",
    "YFI/USDT",
    "RSR/USDT",
    "XVG/USDT",
    "BEAM/USDT",
    "MET/USDT",
    "RVN/USDT",
    "ZRX/USDT",
    "EDU/USDT",
    "KMNO/USDT",
    "KSM/USDT",
]

BASE_SYMBOL = "BTC/USDT"

# OUTPUT CONFIG
SAVE_RESULTS = True
OUTPUT_FILE = "out/cluster_results.csv"

SAVE_REPORT = True
REPORT_FILE = "out/cluster_report.html"

# DATE RANGE
END_DATE = datetime.utcnow()
START_DATE = END_DATE - timedelta(days=DAYS_BACK)